import Layout from "@/components/general/Layout";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider"; // ✅ Add this line
import { Toaster } from 'sonner';

import "./globals.css";

// Use a proper variable name
const ibmFont = IBM_Plex_Sans({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={ibmFont.className}>
        <ReactQueryProvider>
          <Layout>{children}</Layout>
            <Toaster position="top-center" richColors closeButton />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
