import Layout from "@/components/general/Layout";
import type { Metadata } from "next";
import { IBM_Plex_Sans } from "next/font/google";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { Toaster } from "sonner";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";

import "slick-carousel/slick/slick-theme.css"; // if used in this project
import "slick-carousel/slick/slick.css"; // if used in this project
import "../globals.css";

const ibmFont = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
                                               children,
                                           params,
                                         }: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
      <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${ibmFont.variable} antialiased`}>
      <NextIntlClientProvider>
        <ReactQueryProvider>
          <Layout>{children}</Layout>
          <Toaster position="top-center" richColors closeButton />
        </ReactQueryProvider>
      </NextIntlClientProvider>
      </body>
      </html>
  );
}
